server:
  port: 8081  # Changed from 8080 to avoid port conflict

spring:
  # Database Configuration
  datasource:
    url: jdbc:h2:mem:taskdb  # H2 in-memory database URL
    driverClassName: org.h2.Driver  # H2 driver class
    username: sa  # Database username
    password:  # Empty password for development

  # H2 Console Configuration (useful for development)
  h2:
    console:
      enabled: true  # Enable H2 web console
      path: /h2-console  # Console path
      settings:
        web-allow-others: false  # Disable remote access

  # JPA Configuration
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update  # Automatically update database schema
    show-sql: true  # Show SQL queries in logs
    properties:
      hibernate:
        format_sql: true  # Format SQL for better readability

# Logging Configuration
logging:
  level:
    org.springframework: INFO  # Spring framework logging level
    com.example.taskmanager: DEBUG  # Application logging level
    org.hibernate: INFO  # Hibernate logging level 